AWSTemplateFormatVersion: "2010-09-09"
Description: Resources for Rota project
Parameters:
  Stage:
    Type: String
    AllowedValues: [latest, test, beta, prod]
Resources:
  RotaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'ais-${Stage}-rota'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - {AttributeName: teamName, AttributeType: S}
      KeySchema:
        - {AttributeName: teamName, KeyType: HASH}
      Tags:
        -
          Key: tenant
          Value: platform
        -
          Key: stage
          Value: !Ref Stage
        -
          Key: service
          Value: rota
        -
          Key: feature
          Value: rota
        -
          Key: owner
          Value: Mohit K.
